stages:
  - mirror

mirror_to_github:
  stage: mirror
  script:
    - git remote add github https://oauth2:${GITHUB_TOKEN}@github.com/Ville-Eurometropole-Strasbourg/qgis-configuration.git
    - git push --mirror github
  only:
    - main
